ArthurFrederico.SIGA.Web/Controllers/RelatorioController.cs
using ArthurFrederico.SIGA.Model;
using ArthurFrederico.SIGA.Model.DAO;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ArthurFrederico.SIGA.Web.Controllers
{
    [Authorize]
    public class RelatorioController : Controller
    {
        [Route("Relatorio/AlunosPorCidade")]
        [Route("Relatorio/AlunosPorCidade/Cidade{idCidade}")]
        public ActionResult AlunosPorCidade(int idCidade = -1)
        {
            CidadeModelDAO cidadeHandler = new CidadeModelDAO();

            ViewBag.Cidades = cidadeHandler.GetAll();

            if (idCidade == -1)
            {
                return View(new List<AlunoModel>());
            }
            else
            {
                AlunoModelDAO alunoHandler = new AlunoModelDAO();
                return View(alunoHandler.AlunosPorCidade(idCidade));
            }
        }
    }
}

ArthurFrederico.SIGA.Web/Views/Relatorio/AlunosPorCidade.cshtml
@model IEnumerable<ArthurFrederico.SIGA.Model.AlunoModel>

@{
    ViewBag.Title = "Aluno List";
}

<div class="login-box-title">
    <span>Relatorio</span>
</div>
@using (Html.BeginForm("AlunosPorCidade", "Relatorio", FormMethod.Get))
{
    <span>Cidade:</span>
    @Html.DropDownList("idCidade", new SelectList(ViewBag.Cidades, "Id", "Nome"), new { @class = "input-cadastro" })
    <div class="login-footer">
        <button type="submit" id="login-button">Search</button>
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCadastro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CidadeId)
            </th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cpf)
            </td>
            <td>
                @String.Format("{0}", (item.Sexo) ? "Masculino" : "Feminino");
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataCadastro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cidade.Nome)
            </td>
        </tr>
    }

</table>