ArthurFrederico.SIGA.Web/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ArthurFrederico.SIGA.Web.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Insira o Nome!")]
        [Display(Name = "Nome:")]
        public string Nick { get; set; }

        [Required(ErrorMessage = "Insira a Senha!")]
        [Display(Name = "Senha:")]
        public string Senha { get; set; }
    }
}

ArthurFrederico.SIGA.Web/Controllers/AutenticacaoController.cs
using ArthurFrederico.SIGA.Model.DAO;
using ArthurFrederico.SIGA.Web.Models;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using System.Web.Security;

namespace ArthurFrederico.SIGA.Web.Controllers
{
    public class AutenticacaoController : Controller
    {
        // GET: Autenticacao
        [HttpGet]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View(new LoginViewModel());
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel login, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                UsuarioModelDAO usuarioHandler = new UsuarioModelDAO();

                var user = usuarioHandler.Find(login.Nick);
                if (user != null)
                {
                    var encryptor = SHA512.Create();
                    var pass = Encoding.UTF8.GetString(encryptor.ComputeHash(Encoding.UTF8.GetBytes(login.Senha + user.Cpf)));
                    if (user.HashSenha == pass)
                    {
                        FormsAuthentication.SetAuthCookie(user.Nome, false);

                        if (!string.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
                        {
                            return Redirect(returnUrl);
                        }
                        else
                        {
                            return Redirect("/");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("ModelError", "Usuário e senha não conferem!");
                    }
                }
                else
                {
                    ModelState.AddModelError("ModelError", "Usuário e senha não conferem!");
                }
            }

            ViewBag.ReturnUrl = returnUrl;
            return View(new LoginViewModel());
        }
    }
}

ArthurFrederico.SIGA.Web/Controllers/UsuarioController.cs
using ArthurFrederico.SIGA.Model;
using ArthurFrederico.SIGA.Model.DAO;
using System;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;

namespace ArthurFrederico.SIGA.Web.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            CidadeModelDAO cidadeHandler = new CidadeModelDAO();

            ViewBag.Cidades = cidadeHandler.GetAll();

            return View(new UsuarioModel());
        }

        [HttpPost]
        public ActionResult Create(UsuarioModel usuario)
        {
            CidadeModelDAO cidadeHandler = new CidadeModelDAO();

            ViewBag.Cidades = cidadeHandler.GetAll();

            if (ModelState.IsValid)
            {
                UsuarioModelDAO usuarioHandler = new UsuarioModelDAO();

                var encryptor = SHA512.Create();
                usuario.HashSenha = Encoding.UTF8.GetString(encryptor.ComputeHash(Encoding.UTF8.GetBytes(usuario.HashSenha + usuario.Cpf)));
                usuario.DataCadastro = DateTime.Now;
                try
                {
                    usuarioHandler.Add(usuario);

                    return RedirectToAction("Login", "Autenticacao");
                }
                catch (Exception e)
                {

                    ModelState.AddModelError("ModelError", "Erro ao efetuar o cadastro, seu cadastro pode já ter sido efetuado ou algum dado pode ter sido inserido incorretamente.");
                }
            }

            return View(usuario);
        }
    }
}

ArthurFrederico.SIGA.Web/Views/Autenticacao/Login.cshtml
@model ArthurFrederico.SIGA.Web.Models.LoginViewModel

@{
    Layout = null;
    ViewBag.Title = "Login";
}
<!DOCTYPE html>
<html>
    <head>
        <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
        <title>Login</title>
    </head>
    <body>

        <div class="login-box">
            <div class="login-box-title">
                <span>S.I.G.A</span>
            </div>
            <div class="login-box-desc">
                <span>Sistema Integrado de Gestão de Alunos</span>
            </div>
            <div class="line"></div>

            <div class="form">

                @using (Html.BeginForm("Login", "Autenticacao", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "" }))
                {
                    <div class="form-input">
                        <span class="email-label">
                            E-mail
                        </span>
                        @Html.TextBoxFor(model => model.Nick, new { @class = "input-default", placeholder = "Nome, Email, CPF, Fone", name = "email" })
                        @Html.ValidationMessageFor(model => model.Nick, "", new { @class = "", style = "color : red;" })
                        <span class="password-label" id="passwordSpan">
                            Senha
                        </span>
                        @Html.PasswordFor(model => model.Senha, new { @class = "input-default", name = "password", id = "passwordInput", placeholder = "Senha" })
                        @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "", style = "color : red;" })
                    </div>

                    <div class="error-message">
                        @Html.ValidationMessage("ModelError")
                    </div>

                    <div class="login-footer">
                        <span class="register-span">Ainda não tem conta? @Html.ActionLink("Cadastre-se aqui!", "Create", "Usuario", new { }, new { @class = "register-link" })</span>
                        <button type="submit" id="login-button">Entrar</button>
                    </div>
                }
            </div>
        </div>
    </body>
</html>