ArthurFrederico.SIGA.Web/Controllers/CidadeController.cs
using ArthurFrederico.SIGA.Model;
using ArthurFrederico.SIGA.Model.DAO;
using ArthurFrederico.SIGA.Web.Models;
using System;
using System.Web.Mvc;

namespace ArthurFrederico.SIGA.Web.Controllers
{
    [Authorize]
    public class CidadeController : Controller
    {
        public const int ItensPorPagina = 5;

        [Route("Cidade/Pagina{pagina}")]
        [Route("Cidade/List/Pagina{pagina}")]
        public ActionResult List(int pagina = 1, string nome = "", string estado = "", string cep = "")
        {
            CidadeModelDAO cidadeHandler = new CidadeModelDAO();

            ViewBag.Paginacao = new Paginacao()
            {
                PaginaAtual = pagina,
                ItensPorPagina = ItensPorPagina,
                TotalItens = cidadeHandler.SearchCount(nome, estado, cep)
            };

            return View(cidadeHandler.GetCidadeList(ItensPorPagina, pagina, nome, estado, cep));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CidadeModel cidade)
        {
            if (ModelState.IsValid)
            {
                CidadeModelDAO cidadeHandler = new CidadeModelDAO();
                try
                {
                    cidadeHandler.Add(cidade);
                }
                catch (Exception)
                {
                    ModelState.AddModelError("ModelError", "Erro ao efetuar o cadastro, seu cadastro pode já ter sido efetuado ou algum dado pode ter sido inserido incorretamente.");
                }
                return RedirectToAction("List");
            }

            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            CidadeModelDAO cidadeHandler = new CidadeModelDAO();

            return View(cidadeHandler.GetCidade(id));
        }

        [HttpPost]
        public ActionResult Edit(CidadeModel cidade)
        {
            if (ModelState.IsValid)
            {
                CidadeModelDAO cidadeHandler = new CidadeModelDAO();
                try
                {
                    cidadeHandler.Update(cidade);
                    return RedirectToAction("List", new { pagina = 1 });
                }
                catch (Exception)
                {
                    ModelState.AddModelError("ModelError", "Erro ao efetuar o update, algum dado pode ter sido inserido incorretamente.");
                }
            }

            return View(cidade);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            CidadeModelDAO cidadeHandler = new CidadeModelDAO();

            try
            {
                cidadeHandler.Delete(id);
            }
            catch (Exception)
            {

                throw;
            }
            
            return RedirectToAction("List");
        }
    }
}

ArthurFrederico.SIGA.Web/Views/Cidade/Create.cshtml
@model ArthurFrederico.SIGA.Model.CidadeModel

@{
    ViewBag.Title = "Create";
}

<div class="login-box-title">
    <span>
        Create
    </span>
</div>

@Html.ValidationMessage("ModelError")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="login-box-desc">
            <span>Cidade</span>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Cep, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Cep, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Cep, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="login-footer">
            <button type="submit" id="login-button">Create</button>
        </div>

        <div class="form-link">
            @Html.ActionLink("Back to List", "List")
        </div>
    </div>
}

ArthurFrederico.SIGA.Web/Views/Cidade/Edit.cshtml
@model ArthurFrederico.SIGA.Model.CidadeModel

@{
    ViewBag.Title = "Edit";
}

<div class="login-box-title">
    <span>
        Edit
    </span>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="login-box-desc">
            <span>Cidade</span>
        </div>
        <div class="line"></div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Cep, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Cep, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Cep, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="login-footer">
            <button type="submit" id="login-button">Edit</button>
        </div>

        <div class="form-link">
            @Html.ActionLink("Back to List", "List")
        </div>
    </div>
}

ArthurFrederico.SIGA.Web/Views/Cidade/List.cshtml
@model IEnumerable<ArthurFrederico.SIGA.Model.CidadeModel>

@{
    ViewBag.Title = "List";
}

<div class="login-box-title">
    <span>List</span>
</div>

<div class="form-link">
    @Html.ActionLink("Create New", "Create")
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cep)
            </th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cep)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>
@using (Html.BeginForm("List", "Cidade", new { pagina = 1 }, FormMethod.Get))
{
    <div class="area-pesquisa-3">
        <div class="cell-pesquisa-3">
        @Html.TextBox("nome", "", new { placeholder = "Nome", @type = "search" })
        </div>

        <div class="cell-pesquisa-3">
        @Html.TextBox("estado", "", new { placeholder = "Estado", @type = "search" })
        </div>

        <div class="cell-pesquisa-3">
        @Html.TextBox("cep", "", new { placeholder = "CEP", @type = "search" })
        </div>
    </div>
    <div class="login-footer">
        <button type="submit" id="login-button">Search</button>
    </div>
}

<div class="pagination">
    @Html.CreatePaginacaoLinks((ArthurFrederico.SIGA.Web.Models.Paginacao)ViewBag.Paginacao,
    x => Url.Action("List", new {
        pagina = x,
        nome = Request.Params["nome"],
        estado = Request.Params["estado"],
        cep = Request.Params["cep"]
    }))
</div>