ArthurFrederico.SIGA.Web/Controllers/AlunoController.cs
using ArthurFrederico.SIGA.Model;
using ArthurFrederico.SIGA.Model.DAO;
using ArthurFrederico.SIGA.Web.Models;
using System;
using System.Web.Mvc;

namespace ArthurFrederico.SIGA.Web.Controllers
{
    [Authorize]
    public class AlunoController : Controller
    {
        public const int ItensPorPagina = 5;

        [Route("Aluno/Pagina{pagina}")]
        [Route("Aluno/List/Pagina{pagina}")]
        public ActionResult List(int pagina = 1, int id = -1, string nome = "", string cpf = "", string dataNascimento = "", string dataCadastro = "")
        {
            AlunoModelDAO alunoHandler = new AlunoModelDAO();

            ViewBag.Paginacao = new Paginacao()
            {
                PaginaAtual = pagina,
                ItensPorPagina = ItensPorPagina,
                TotalItens = alunoHandler.SearchCount(id, nome, cpf, dataNascimento, dataCadastro)
            };

            return View(alunoHandler.GetList(ItensPorPagina, pagina, id, nome, cpf, dataNascimento, dataCadastro));
        }

        [HttpGet]
        public ActionResult Create()
        {
            CidadeModelDAO cidadeHandler = new CidadeModelDAO();

            ViewBag.Cidades = cidadeHandler.GetAll();

            return View(new CreateAlunoViewModel() { Aluno = new AlunoModel(), Tutor1 = new TutorModel(), Tutor2 = new TutorModel() });
        }

        [HttpPost]
        public ActionResult Create(CreateAlunoViewModel viewModel)
        {
            CidadeModelDAO cidadeHandler = new CidadeModelDAO();

            ViewBag.Cidades = cidadeHandler.GetAll();

            if (ModelState.IsValid)
            {
                TutorModelDAO tutorHandler = new TutorModelDAO();
                AlunoModelDAO alunoHandler = new AlunoModelDAO();

                var tutor1 = tutorHandler.Find(viewModel.Tutor1.Cpf);
                if (tutor1 == null)
                {
                    tutor1 = viewModel.Tutor1;
                    tutor1.DataCadastro = DateTime.Now;

                    try
                    {
                        tutorHandler.Add(viewModel.Tutor1);
                    }
                    catch (Exception e)
                    {
                        ModelState.AddModelError("ModelError", "Erro ao efetuar o cadastro, algum dado pode ter sido inserido incorretamente.");
                        return View(viewModel);
                    }
                }

                var tutor2 = tutorHandler.Find(viewModel.Tutor2.Cpf);
                if (tutor2 == null)
                {
                    tutor2 = viewModel.Tutor2;
                    tutor2.DataCadastro = DateTime.Now;

                    try
                    {
                        tutorHandler.Add(viewModel.Tutor2);
                    }
                    catch (Exception e)
                    {
                        ModelState.AddModelError("ModelError", "Erro ao efetuar o cadastro, algum dado pode ter sido inserido incorretamente.");
                        return View(viewModel);
                    }
                }

                viewModel.Aluno.Tutor1Id = tutor1.Id;
                viewModel.Aluno.Tutor2Id = tutor2.Id;

                DateTime now = DateTime.Today;
                int idade = now.Year - viewModel.Aluno.DataNascimento.Year;
                if (now < viewModel.Aluno.DataNascimento.AddYears(idade)) idade--;

                viewModel.Aluno.Idade = idade;
                viewModel.Aluno.DataCadastro = DateTime.Now;
                viewModel.Aluno.DataUltimaModificacao = DateTime.Now;
                viewModel.Aluno.UsuarioModificacao = User.Identity.Name;

                try
                {
                    alunoHandler.Add(viewModel.Aluno);
                    return RedirectToAction("List");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("ModelError", "Erro ao efetuar o cadastro, algum dado pode ter sido inserido incorretamente.");
                }
            }

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            AlunoModelDAO alunoHandler = new AlunoModelDAO();
            CidadeModelDAO cidadeHandler = new CidadeModelDAO();

            ViewBag.Cidades = cidadeHandler.GetAll();

            return View(alunoHandler.Find(id));
        }


        [HttpPost]
        public ActionResult Edit(AlunoModel aluno)
        {
            AlunoModelDAO alunoHandler = new AlunoModelDAO();
            CidadeModelDAO cidadeHandler = new CidadeModelDAO();

            ViewBag.Cidades = cidadeHandler.GetAll();

            if (ModelState.IsValid)
            {
                aluno.DataUltimaModificacao = DateTime.Now;
                aluno.UsuarioModificacao = User.Identity.Name;

                try
                {
                    alunoHandler.Update(aluno);
                    return RedirectToAction("List");
                }
                catch (Exception)
                {
                    ModelState.AddModelError("ModelError", "Erro ao efetuar a edição, algum dado pode ter sido inserido incorretamente.");
                }

            }

            return View(aluno);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            AlunoModelDAO alunoHandler = new AlunoModelDAO();

            try
            {
                alunoHandler.Delete(id);
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("List");
        }
    }
}

ArthurFrederico.SIGA.Web/Views/Aluno/Create.cshtml
@model ArthurFrederico.SIGA.Web.Models.CreateAlunoViewModel

@{
    ViewBag.Title = "Create";
}

<div class="login-box-title">
    <span>
        Create
    </span>
</div>

@Html.ValidationMessage("ModelError")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="login-box-desc">
            <span>Anuno</span>
        </div>
        <div class="line"></div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Aluno.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Aluno.Nome, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Aluno.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Aluno.Rg, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Aluno.Rg, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Aluno.Rg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Aluno.Cpf, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Aluno.Cpf, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Aluno.Cpf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Aluno.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Aluno.DataNascimento, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Aluno.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div id="tutor1">
            <div class="line"></div>
            <div class="login-box-desc">
                <span>@Html.LabelFor(model => model.Aluno.Tutor1Id, htmlAttributes: new { @class = "" })</span>
            </div>
            <div class="line"></div>
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-input-cadastro">
                    @Html.LabelFor(model => model.Tutor1.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Tutor1.Nome, new { htmlAttributes = new { @class = "input-cadastro" } })
                    <div class="error-message">
                        @Html.ValidationMessageFor(model => model.Tutor1.Nome, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-input-cadastro">
                    @Html.LabelFor(model => model.Tutor1.Rg, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Tutor1.Rg, new { htmlAttributes = new { @class = "input-cadastro" } })
                    <div class="error-message">
                        @Html.ValidationMessageFor(model => model.Tutor1.Rg, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-input-cadastro">
                    @Html.LabelFor(model => model.Tutor1.Cpf, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Tutor1.Cpf, new { htmlAttributes = new { @class = "input-cadastro" } })
                    <div class="error-message">
                        @Html.ValidationMessageFor(model => model.Tutor1.Cpf, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-input-cadastro">
                    @Html.LabelFor(model => model.Tutor1.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="checkbox">
                        @Html.Label("Masculino:")
                        @Html.RadioButtonFor(model => model.Tutor1.Sexo, true)
                        @Html.Label("Feminino:")
                        @Html.RadioButtonFor(model => model.Tutor1.Sexo, false)
                        <div class="error-message">
                            @Html.ValidationMessageFor(model => model.Tutor1.Sexo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-input-cadastro">
                    @Html.LabelFor(model => model.Tutor1.Profissao, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Tutor1.Profissao, new { htmlAttributes = new { @class = "input-cadastro" } })
                    <div class="error-message">
                        @Html.ValidationMessageFor(model => model.Tutor1.Profissao, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-input-cadastro">
                    @Html.LabelFor(model => model.Tutor1.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Tutor1.Telefone, new { htmlAttributes = new { @class = "input-cadastro" } })
                    <div class="error-message">
                        @Html.ValidationMessageFor(model => model.Tutor1.Telefone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="line"></div>
            </div>
        </div>

        <div id="tutor2">
            <div class="login-box-desc">
                <span>@Html.LabelFor(model => model.Aluno.Tutor2Id, htmlAttributes: new { @class = "" })</span>
            </div>
            <div class="form-horizontal">
                <div class="line"></div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-input-cadastro">
                    @Html.LabelFor(model => model.Tutor2.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Tutor2.Nome, new { htmlAttributes = new { @class = "input-cadastro" } })
                    <div class="error-message">
                        @Html.ValidationMessageFor(model => model.Tutor2.Nome, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-input-cadastro">
                    @Html.LabelFor(model => model.Tutor2.Rg, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Tutor2.Rg, new { htmlAttributes = new { @class = "input-cadastro" } })
                    <div class="error-message">
                        @Html.ValidationMessageFor(model => model.Tutor2.Rg, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-input-cadastro">
                    @Html.LabelFor(model => model.Tutor2.Cpf, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Tutor2.Cpf, new { htmlAttributes = new { @class = "input-cadastro" } })
                    <div class="error-message">
                        @Html.ValidationMessageFor(model => model.Tutor2.Cpf, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-input-cadastro">
                    @Html.LabelFor(model => model.Tutor2.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="checkbox">
                        @Html.Label("Masculino:")
                        @Html.RadioButtonFor(model => model.Tutor2.Sexo, true)
                        @Html.Label("Feminino:")
                        @Html.RadioButtonFor(model => model.Tutor2.Sexo, false)
                        <div class="error-message">
                            @Html.ValidationMessageFor(model => model.Tutor2.Sexo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-input-cadastro">
                    @Html.LabelFor(model => model.Tutor2.Profissao, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Tutor2.Profissao, new { htmlAttributes = new { @class = "input-cadastro" } })
                    <div class="error-message">
                        @Html.ValidationMessageFor(model => model.Tutor2.Profissao, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-input-cadastro">
                    @Html.LabelFor(model => model.Tutor2.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Tutor2.Telefone, new { htmlAttributes = new { @class = "input-cadastro" } })
                    <div class="error-message">
                        @Html.ValidationMessageFor(model => model.Tutor2.Telefone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="line"></div>
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Aluno.EnderecoCompleto, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Aluno.EnderecoCompleto, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Aluno.EnderecoCompleto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Aluno.CidadeId, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.DropDownListFor(model => model.Aluno.CidadeId, new SelectList(ViewBag.Cidades, "Id", "Nome"), new { @class = "input-cadastro" })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Aluno.Cidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Aluno.Matricula, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Aluno.Matricula, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Aluno.Matricula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Aluno.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="checkbox">
                @Html.Label("Masculino:")
                @Html.RadioButtonFor(model => model.Aluno.Sexo, true)
                @Html.Label("Feminino:")
                @Html.RadioButtonFor(model => model.Aluno.Sexo, false)
                <div class="error-message">
                    @Html.ValidationMessageFor(model => model.Aluno.Sexo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Aluno.Telefone1, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Aluno.Telefone1, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Aluno.Telefone1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Aluno.Telefone2, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Aluno.Telefone2, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Aluno.Telefone2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Aluno.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Aluno.Email, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Aluno.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="login-footer">
            <button type="submit" id="login-button">Create</button>
        </div>

        <div class="form-link">
            @Html.ActionLink("Back to List", "List")
        </div>
    </div>
}

ArthurFrederico.SIGA.Web/Views/Aluno/Edit.cshtml
@model ArthurFrederico.SIGA.Model.AlunoModel

<div class="login-box-title">
    <span>
        Edit
    </span>
</div>

@Html.ValidationMessage("ModelError")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <div class="login-box-desc">
            <span>Anuno</span>
        </div>
        <div class="line"></div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Rg, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Rg, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Rg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Cpf, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Cpf, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Cpf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.EnderecoCompleto, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.EnderecoCompleto, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.EnderecoCompleto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="checkbox">
                    @Html.Label("Masculino:")
                    @Html.RadioButtonFor(model => model.Sexo, true)
                    @Html.Label("Feminino:")
                    @Html.RadioButtonFor(model => model.Sexo, false)
            <div class="error-message">
                    @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Telefone1, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Telefone1, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Telefone1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Telefone2, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Telefone2, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Telefone2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.CidadeId, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DropDownListFor(model => model.CidadeId, new SelectList(ViewBag.Cidades, "Id", "Nome"), new { @class = "input-cadastro" })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-input-cadastro">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "input-cadastro" } })
            <div class="error-message">
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="login-footer">
            <button type="submit" id="login-button">Edit</button>
        </div>

        <div class="form-link">
            @Html.ActionLink("Back to List", "List")
        </div>
    </div>
}

ArthurFrederico.SIGA.Web/Views/Aluno/List.cshtml
@model IEnumerable<ArthurFrederico.SIGA.Model.AlunoModel>

@{
    ViewBag.Title = "Aluno List";
}

<div class="login-box-title">
    <span>List</span>
</div>

<div class="form-link">
    @Html.ActionLink("Create New", "Create")
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCadastro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CidadeId)
            </th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cpf)
            </td>
            <td>
                @String.Format("{0}", (item.Sexo) ? "Masculino" : "Feminino");
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataCadastro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cidade.Nome)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

@using (Html.BeginForm("List", "Aluno", new { pagina = 1 }, FormMethod.Get))
{
    <div class="area-pesquisa-5">
        <div class="cell-pesquisa-5">
            @Html.TextBox("id", "", new { placeholder = "Código", @type = "search" })
        </div>

        <div class="cell-pesquisa-5">
            @Html.TextBox("nome", "", new { placeholder = "Nome", @type = "search" })
        </div>

        <div class="cell-pesquisa-5">
            @Html.TextBox("cpf", "", new { placeholder = "CPF", @type = "search" })
        </div>

        <div class="cell-pesquisa-5">
            @Html.TextBox("dataNascimento", "", new { placeholder = "Data de Nascimento", @type = "search" })
        </div>

        <div class="cell-pesquisa-5">
            @Html.TextBox("dataCadastro", "", new { placeholder = "Data de Cadastro", @type = "search" })
        </div>
    </div>
    <div class="login-footer">
        <button type="submit" id="login-button">Search</button>
    </div>
}

<div class="pagination">
    @Html.CreatePaginacaoLinks((ArthurFrederico.SIGA.Web.Models.Paginacao)ViewBag.Paginacao,
    x => Url.Action("List", new {
        pagina = x,
        id = Request.Params["id"],
        nome = Request.Params["nome"],
        cpf = Request.Params["cpf"],
        dataNascimento = Request.Params["dataNascimento"],
        dataCadastro = Request.Params["dataCadastro"]
    }))
</div>

ArthurFrederico.SIGA.Web/Views/Aluno/Tutor.cshtml
@model ArthurFrederico.SIGA.Model.TutorModel

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Rg, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Rg, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Rg, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cpf, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cpf, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cpf, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.Label("Masculino:")
                @Html.RadioButtonFor(model => model.Sexo, true)
                @Html.Label("Feminino:")
                @Html.RadioButtonFor(model => model.Sexo, false)
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Profissao, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Profissao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Profissao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
        </div>
    </div>

    <hr />
</div>